### ISSUE TITLE
compute cos(ine)

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#2]
I've got my pmiMX but failed to compute the cosine distances.
I imported MatrixManager already and the pmi weighted matrix seems alright.

According to the tutorial the method is compute_cos() but I get this:
```
>>> cos_mx = MatrixManager.compute_cos(pmiMX)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: class MatrixManager has no attribute 'compute_cos'
```

On the python script (Manager.py) the method is called compute_cosine() but I get this:
```
>>> cos_mx = MatrixManager.compute_cosine(pmiMX)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aardvark/code/typetokenQLVL/typetoken/utils.py", line 15, in timer
    result = fn(*args, **kwargs)
  File "/home/aardvark/code/typetokenQLVL/typetoken/Manager.py", line 199, in compute_cosine
    cosMX = cosine_similarity(pmx)
  File "/home/aardvark/tools/VENV/PY_VENV/lib/python2.7/site-packages/sklearn/metrics/pairwise.py", line 917, in cosine_similarity
    X, Y = check_pairwise_arrays(X, Y)
  File "/home/aardvark/tools/VENV/PY_VENV/lib/python2.7/site-packages/sklearn/metrics/pairwise.py", line 107, in check_pairwise_arrays
    warn_on_dtype=warn_on_dtype, estimator=estimator)
  File "/home/aardvark/tools/VENV/PY_VENV/lib/python2.7/site-packages/sklearn/utils/validation.py", line 433, in check_array
    array = np.array(array, dtype=dtype, order=order, copy=copy)
ValueError: setting an array element with a sequence.
```

**Comment by enzocxt** [comment]
Sorry, there is a small bug in code.
Although I think I have fixed the code a minute ago, could you please check with the following code first:
```python
cos_mx = MatrixManager.compute_cosine(pmi_mx)
```
Here the pmi_mx is the scipy sparse matrix you previously created. And the pmiMX is an object of WCMatrix. If this works, then try with your posted code.
The code should work for both pmi_mx and pmiMX (scipy sparse matrix and object of WCMatrix) as input. But there is a bug with WCMatrix as input.
Thanks.

**Comment by enzocxt** [comment]
What is your pmi matrix file size, and the dimension of your pmi matrix (num_rows X num_columns)?
If the dimension of pmi / cosine matrix is large, then the file size of your consine matrix would be very large.
So please be careful when you are dealing with very large matrix :-)

**Comment by delhikiev** [comment]
Indeed, it had about 60k rows. I tried again with 5k x 10k and it was quite straightforward.
