### ISSUE TITLE
Selecting most frequent words in freqDict

### ISSUE THREAD

**Issue by delhikiev** [QLVL/QLVL-softwiki#8]
The freqDict object has no predefined order, so slicing it does not guarantee that the most frequent worders will be preserved.
`freqDict[50:]` will not necessarily eliminate the 50 most frequent items, and `freqDict[:5000]` will not necessarily keep the 5000 most frequent.

I found the keep_most_n() method on Dict.py (it's not on the tutorial, so it's a kind of wild guess), which looks like it's meant to achieve what I need, but I get the following error message:

```
>>> noun5k = fd1[fd1.keep_most_n(n=5050)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aardvark/code/typetokenQLVL/typetoken/Dict.py", line 118, in __getitem__
    raise NotImplementedError("Error: unimplemented type!")
NotImplementedError: Error: unimplemented type!
```

**Comment by delhikiev** [comment]
sorry, it works if it's not used as other filters:
`noun5k = fd1.keep_most_n(n=5000)`
